### ISSUE TITLE
Feature: Add more ad networks to increase overall package visibility

### ISSUE THREAD

**Issue by foreza** [MFlisar/GDPRDialog#12]
Hi,

I was following your library and I'm really enjoying what I'm seeing here.
I just recently joined the adtech industry (junior dev here) and still learning the ropes.

My suggestion (minor) is to add strings / text / links for the other ad networks, like MoPub / Vungle / Unity as those have a pretty healthy following.

**Comment by MFlisar** [comment]
Simply provide their privacy policy links and I can add them (or add them via a pull request)

**Comment by foreza** [comment]
Hey @MFlisar ,

See below. I can add more as I come across them.
I work on a mediation SDK right now, so I mess around with adapters and such.

https://github.com/MFlisar/GDPRDialog/pull/13

**Comment by MFlisar** [comment]
Thanks, so I will close this
