### ISSUE TITLE
Wrong strings

### ISSUE THREAD

**Issue by Luklek** [MFlisar/GDPRDialog#2]
String text2 = activity.getString(R.string.gdpr_dialog_text_part2, mSetup.explicitAgeConfirmation() ? activity.getString(R.string.gdpr_dialog_text_part2_no_age) : activity.getString(R.string.gdpr_dialog_text_part2_with_age));

gdpr_dialog_text_part2_no_age and gdpr_dialog_text_part2_with_age have a different name in English strings (but it's correct in DE)

**Comment by MFlisar** [comment]
thanks, will fix this in the next commit and release v0.4 in the evening today
