### ISSUE TITLE
Clipped text

### ISSUE THREAD

**Issue by MMarco94** [MFlisar/GDPRDialog#21]
Using the bottom dialog layout in italian on a 1920x1080 screen (320dp width), the text is partially clipped.

Not a major issue, but I think fixing it will be easy.

**Comment by Goomba** [comment]
![photo_2018-05-24_20-55-57](https://user-images.githubusercontent.com/802019/40505792-a62dff66-5f95-11e8-8989-f986389d5f50.jpg)

**Comment by Luklek** [comment]
gdpr_dialog_text2_plural has an error "Usaimo" instead of "Usiamo"

**Comment by Goomba** [comment]
You are right, I created a pull request

**Comment by MFlisar** [comment]
Typo is already fixed in the master branch.

Which android version are you using? Android 8 or higher maybe?

**Comment by Goomba** [comment]
Android 8.0.0

**Comment by MFlisar** [comment]
On android 8 I use the `textView.setJustificationMode(Layout.JUSTIFICATION_MODE_INTER_WORD);` function of the `TextView` which was added in this version, maybe it's not perfectly working though... In this case I will remove this again

**Comment by Goomba** [comment]
Before removing it, please allow me to do some testing. I'll get back to you in a few hours.

**Comment by MFlisar** [comment]
Thanks for the feedback, so I will use the second method only

**Comment by MFlisar** [comment]
done in the master branch
