### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MMarco94** [MFlisar/GDPRDialog#23]
I keep getting crashes like this:
`java.lang.IllegalStateException: 
  at android.support.v4.app.FragmentManagerImpl.enqueueAction (SourceFile:2087)
  at android.support.v4.app.BackStackRecord.commitInternal (SourceFile:678)
  at android.support.v4.app.BackStackRecord.commit (SourceFile:632)
  at android.support.v4.app.DialogFragment.show (SourceFile:143)
  at com.michaelflisar.gdprdialog.GDPR.showDialog (SourceFile:167)`

The issue seems to appear on Samsung Galaxy J7 and J5.

**Comment by MFlisar** [comment]
Have you forgettens something like this maybe?

    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss...

**Comment by MMarco94** [comment]
No, the stacktrace ends there

**Comment by MFlisar** [comment]
There is no text after the exception??

Only idea is to replace following

    dlg.show(activity.getSupportFragmentManager(), GDPRDialog.class.getName());

with
    
    activity.getSupportFragmentManager().beginTransaction().add(dlg, GDPRDialog.class.getName()).commitAllowingStateLoss();

Can you reproduce the issue? I assume it happens if the activity is destroyed while the dialog tries to be shown...

**Comment by MMarco94** [comment]
I cannot reproduce the issue, unfortunately. No text after the exception. Could be because I'm using ProGuard

**Comment by MFlisar** [comment]
I assume this change will prevent this crash https://github.com/MFlisar/GDPRDialog/commit/e2801d824d1cc76ef3bfb4afd2f37854f0ff870d

**Comment by MFlisar** [comment]
I close this for now, I think this won't happen anymore
