### ISSUE TITLE
Keep a function to add custom networks.

### ISSUE THREAD

**Issue by SoftNirav** [MFlisar/GDPRDialog#24]
I think it's a better idea to keep a function like setup.addCustomNetwork() to add custom networks like answers, crashlytics, or some ad network.
That way someone doesn't need to mess with this project and can add networks (GDPR Definitions) at runtime.

**Comment by MFlisar** [comment]
You can do this, simply define your own `GDPRNetwork`. No need to add them to the definitions...

**Comment by SoftNirav** [comment]
Sorry, I don't know how I missed that. Defining my own GDPRNetwork worked.

**Comment by MFlisar** [comment]
No problem. You probably assumed the definitions are enums ;-)
