### ISSUE TITLE
the dialog does not appear

### ISSUE THREAD

**Issue by NikiHard** [MFlisar/GDPRDialog#25]
what am I doing wrong? my code
```
       GDPRSetup mSetup = new GDPRSetup(GDPRDefinitions.ADMOB, GDPRDefinitions.FIREBASE_ANALYTICS);
        mSetup.withCheckRequestLocation(false);
        GDPR.getInstance().checkIfNeedsToBeShown(this, mSetup);
```

and this 
```
    @Override
    public void onConsentNeedsToBeRequested(GDPRLocation location) {
        // we need to get consent, so we show the dialog here
        GDPR.getInstance().showDialog(this, mSetup, location);
    }
```

**Comment by MFlisar** [comment]
Are you showing the dialog again after user have made a decision? Then that's how it should be... It will only be shown again if you reset the user decision via `GDPR.getInstance().resetConsent()`, then the dialog will be shown again.

**Comment by NikiHard** [comment]
all the same is not displayed

**Comment by MFlisar** [comment]
here's a quite simple working example: https://github.com/MFlisar/GDPRDialog/blob/master/app/src/main/java/com/michaelflisar/gdprdialog/demo/DemoActivity.java

I don't see a big difference, you would need to debug this yourself... No idea what's the problem if it's not that you already know the consent... If the dialog is not shown, you should get the saved consent in the `void onConsentInfoUpdate(GDPRConsentState consentState, boolean isNewState)` callback

**Comment by MFlisar** [comment]
Here's a minimal example to start with now without any overhead: [MinimalExampleActivity](https://github.com/MFlisar/GDPRDialog/blob/master/app/src/main/java/com/michaelflisar/gdprdialog/demo/MinimalDemoActivity.java)

If possible, let me know what your problem was

**Comment by NikiHard** [comment]
my mistake, in another Activity
```
@Override
    public void onConsentNeedsToBeRequested() {
        // forward the result and show the dialog
        
    }
```
