### ISSUE TITLE
Admob and consent SDK.

### ISSUE THREAD

**Issue by SoftNirav** [MFlisar/GDPRDialog#27]
In the readme there is no clarity if the Consent SDK provided by Google should be used with this GDPR Dialog. Or the consent should be sent directly to PublisherAdRequest of Google Mobile Ads SDK.
Is this project meant to replace Consent SDK or is a 'Publisher-managed consent collection' utility.
I also don't understand how GDPR Dialog obtains EEA location data.

**Comment by MFlisar** [comment]
I use the same urls to query Google's data and just interpreted the json response myself. This way I do the same as the sdk to retrieve your admob ad networks and your location

This is a replacement and the consent retrieved via this library should be manually passed to your ad request

**Comment by SoftNirav** [comment]
Thanks a lot. I was a bit worried as I am going to use this in a production release.
I want the list of 600+ sub networks and Google's consent utility supports just 12.
Release 1.0 of GDPR Dialog dosen't support withLoadAdMobNetworks(publisherId(s)) and it's a requirement as per GDPR AFAIK.
I hope using the master build will not have issues though.

**Comment by MFlisar** [comment]
I'll make a release in the evening. Feel free to test it though in the meantime...

600 networks? I think Google will only select 200 for you if you have not selected any thing yourself...

**Comment by SoftNirav** [comment]
Oh thanks! Google is showing only 200 providers in 'Commonly used set of ad technology providers'.
I can't wait till the evening there as it's gonna going to be night here!

**Comment by MFlisar** [comment]
How do you want to create the most of 600+ networks? Manually? The sdk does not return more than the commonly used ones...

**Comment by MFlisar** [comment]
Issue is solved I think, so I close it
