### ISSUE TITLE
CheckRequestLocation

### ISSUE THREAD

**Issue by NikiHard** [MFlisar/GDPRDialog#28]
Whatever parameter I set, the window is always displayed
`mSetup.withCheckRequestLocation(true); //or false`
How to make it only visible to EU users

**Comment by MFlisar** [comment]
How do you test this? Set the parameter to `true` then you should only see the dialog from within the EAA or if the location can't be checked (no internet, timeout, ...)

**Comment by NikiHard** [comment]
i set the parameter to `true` .
I always have a `locaton: unknown `
permission `android.permission.INTERNET` there is

**Comment by MFlisar** [comment]
Did you wait for the response? Dialog will onl show after the request is finished so it depends on your internet speed...

Otherwise simply debug it and check what happens in this line and if this works successful:

https://github.com/MFlisar/GDPRDialog/blob/34e76d0e8e435709c56d66cfd39c6989dfe6ec0f/library/src/main/java/com/michaelflisar/gdprdialog/helper/PreperationAsyncTask.java#L30

**Comment by randomhay** [comment]
I set `mSetup.withCheckRequestLocation(true)`
I am not in EEA.
But it still show dialog to get consent from user.

**Comment by Luklek** [comment]
It's the same for me.
Location shows correctly as NOT_IN_EAA but the consent dialog is shown every time.

**Comment by randomhay** [comment]
please fix it and support set test with EEA and not EEA.

Thank so much for your help !

**Comment by MFlisar** [comment]
Tests will not be supported by me. Simple change the location of the data before you pass it to the show dialog function...

I will check later why the dialog is shown if you are not in EAA...

**Comment by MFlisar** [comment]
I added a consent state: `GDPRConsent.AUTOMATIC_PERSONAL_CONSENT` and a function to the enum `ConsentState.isPersonalConsent()`...

I think it works now, but maybe you test it as well...

**Comment by NikiHard** [comment]
in the latest version it seems to work

**Comment by Luklek** [comment]
Everything seems to be working.

**Comment by MFlisar** [comment]
Great, then I close this
