### ISSUE TITLE
Consent wall is not created.

### ISSUE THREAD

**Issue by SoftNirav** [MFlisar/GDPRDialog#31]
I just noticed that the activity including the ads keep loading in the background while the consent dialogue is shown.
Ideally it should be something like this:
public abstract class MyAppCompatActivity extends AppCompatActivity {
onCreate {
  If (consentRequired) {
     startActivity(consentActivity);
   }
}
I have implemented this in some android app to force users to accept terms.
I am typing on mobile, so please pardon any mistakes.

**Comment by MFlisar** [comment]
The idea is to start loading ads only after consent is known and not before... Simply use the callback's method for this...

**Comment by SoftNirav** [comment]
How frequently is the the callback method run? Does it run everytime the showConsentIfNeeded is run and even if the dialogue is not shown?
And how can we manually set the personalize/non-personalized ads choices if the user chooses so in app settings without opening GDPR Dialog again.

**Comment by MFlisar** [comment]
`showConsentIfNeeded`... use this to show the dialog only, nothing more
`onConsentInfoUpdate(GDPRConsentState consentState, boolean isNewState)`... everytime the consent state is ready, so once after each activity creation...

manual consent state can be set via `GDPR.getInstance().setConsent(consentState);`

**Comment by SoftNirav** [comment]
Ok, thanks a lot.
GDPR.getInstance().checkIfNeedsToBeShown might be triggering the callback.

**Comment by MFlisar** [comment]
It will trigger it always, but it will not always show the dialog. It will indicate if it provides a new state (that was just determined based on location or based on user decision) or an old state via the `isNewState`...

**Comment by SoftNirav** [comment]
I think I will have to rework my implementation, because I have kept separate controls for ads, analytics and crash reporting in app settings and requesting consent for all of them in GDPR Dialog.

**Comment by SoftNirav** [comment]
Does the callback and checkIfNeedsToBeShown() work when a device is offline? I am thinking to display GDPR Dialog immediately after the user presses accept button in my current termsActivity. And when the callback occurs it would mark the acceptance of terms in my current termsActivity.

The Flow: The user would first accept my terms, than go through GDPR dialog to decide on ads, analytics and crash reporting. The user would only (be able to) proceed to any other activity after this.

Other activities would ask only for ads consent in GDPR Dialog (if and when the dialog shows up). I would also be providing separate controls for ads, analytics and crash reporting in app settings and don't want to ask for analytics and crash reporting consent after the first time (the termsActivity flow).

Is the callback reliable enough to occur? I am afraid any user consenting everything again and again being stuck in the termsActivity. Will there be any other issues with this workflow?

**Comment by MFlisar** [comment]
> Does the callback and checkIfNeedsToBeShown() work when a device is offline?

Yes. It will return location unknown and this means consent must be requested

> Is the callback reliable enough to occur?

It will always be called. Either directly or after the location check was done. Check out this code block:

https://github.com/MFlisar/GDPRDialog/blob/6b389921b99cb1035cecba33051c6cefa2e0feca/library/src/main/java/com/michaelflisar/gdprdialog/GDPR.java#L73-L107

If the task is executed, it will always as well execute the callback...

**Tipp**

If an activity can't be accessed if the user has not made a decision yet, simply use following to find out the users decision:

    GDPR.getInstance().getConsent()

**Comment by SoftNirav** [comment]
Thanks. One last question.
If the callback occurs after location check, will it take noticeable time for the user? I am going to do finish my termsActivity and launch mainActivity in callback, after user user presses Accept button to launch GDPR Dialog. If the user is outside EEA and the dialog box is not shown, will the time taken to execute callback be noticeably high?

**Comment by MFlisar** [comment]
It depends on internet speed... Here you can define your own timeouts:

https://github.com/MFlisar/GDPRDialog/blob/0f22acf8e02c340d0630b2ed3f178f66afd1c847/library/src/main/java/com/michaelflisar/gdprdialog/GDPRSetup.java#L159

Be aware, after consent has been given once, it's persistet and it will always be loaded nearly instantly...

**Comment by SoftNirav** [comment]
Thanks, I feel it's a bit risky to rely given the possibility of poor internet connection.
By the way why doesn't this project use the open-source Consent SDK of Google for internal operations and obtaining EEA consent status? It's also licensed under Apache 2.0.
Google would not be able to pour much liability on publishers using their SDK, if it makes mistakes determining EEA status.

**Comment by Luklek** [comment]
You can reduce the timeout and then relay on fallback methods. I am planning to reduce timout to 2000ms myself.
Also even Google consent SDK uses the same address to check location, so the result would be the same with poor internet connection (and without fallback methods ready to use)

**Comment by SoftNirav** [comment]
Why is the consent dialogue shown in the absence of internet connectivity? Ads aren't going to be displayed without internet. Analytics is disabled until consent is obtained. Simply stopping the callback is sufficient. Ever thought of that?

**Comment by SoftNirav** [comment]
AFAIK in absence of internet connectivity admob retries after every few seconds. I have seen that in debug logs months ago. That way whenever it detects connectivity it fetches and displays ads. Not sure although with the consent SDK.

> No internet means you don't know where the user is from so you must show the dialog because he could be from within EAA.
Without internet, ads or analytics won't work. Obtaining consent without internet is useless until internet connection is resumed. And they won't start until callback occurs. Publishers disable analytics until consent is obtained. Callback can be made after internet connection resumes.
This is just a suggestion for a optional future feature.

**Comment by MFlisar** [comment]
You can do following:

@Override
    public void onConsentNeedsToBeRequested(GDPRPreperationData data) {
        if (data.hasError()) {
            // something went wrong, I want to wait until preparation (getting location and/or loading ad mob networks) was successfully; we try it on the next creation of the activity again...
            return;
        }
        GDPR.getInstance().showDialog(this, mSetup, data.getLocation());
    }
