### ISSUE TITLE
BottomSheet INFO PAGE 

### ISSUE THREAD

**Issue by Luklek** [MFlisar/GDPRDialog#32]
Sliding down the BottomSheet Info Page will dismiss the whole consent dialog instead of going back to the main dialog. I think it should go back to the main page even if not forcing the user to consent.

**Comment by MFlisar** [comment]
This would mean you reopen the sheet... That looks intrusive to me...

If you use `withForceSelection` in the `GDPRSetup`, then the bottom sheet can't be swiped down, if not I think current solution is the better choice

**Comment by Luklek** [comment]
Most likely I will not use the BottomSheet and anyway I will use `withForceSelection`.
Was just in case it wasn't intended. Can close :)
