### ISSUE TITLE
Implements Dialog in Settings

### ISSUE THREAD

**Issue by master94ga** [MFlisar/GDPRDialog#34]
Hello, I want to add the possibility to change the consent settings in my app. There is a way yo call the dialog without implementing the interface?
I tried something like this but it crash:

                GDPR.getInstance().init(getActivity());
                GDPRSetup setup = new GDPRSetup(GDPRDefinitions.ADMOB, GDPRDefinitions.FIREBASE_ANALYTICS);
                GDPR.getInstance().showDialog((AppCompatActivity) getActivity(), setup, GDPR.getInstance().getConsentState().getLocation());

I don't need the callback, and I need to show the dialog when the user press the button, not when it need to be show.

**Comment by MFlisar** [comment]
Or do following:
		
	GDPRConsentState consentState = GDPR.getInstance().getConsentState();
	GDPR.getInstance().resetConsent();
	GDPR.getInstance().showDialog(this, mSetup, consentState .getLocation());

No way to avoid that the activity must be implementing the callback interface though currently...

**Comment by master94ga** [comment]
Thanks for the help and the good library.

I used the following method: 

GDPR.getInstance().resetConsent()

After I go back to the previous activity that call the Dialog and it works.

**Comment by MFlisar** [comment]
I just pushed a change to the branch...

Now you can do following in your preferences if this is what you want:

	GDPRConsentState consentState = GDPR.getInstance().getConsentState();
	GDPR.getInstance().resetConsent();
	GDPRDialog dlg = GDPRDialog.newInstance(setup, consentState.getLocation(), false);
	dlg.show(activity.getSupportFragmentManager(), GDPRDialog.class.getName());

Not part of the current release though...
