### ISSUE TITLE
No virtual method isStateSaved() crash

### ISSUE THREAD

**Issue by finalhit** [MFlisar/GDPRDialog#35]
`java.lang.NoSuchMethodError: No virtual method isStateSaved()Z in class Landroid/support/v4/app/FragmentManager; or its super classes
        at com.michaelflisar.gdprdialog.GDPR.showDialog(GDPR.java:167)`

Targeting SDK 25 and using support lib 25.4.0.

**Comment by MFlisar** [comment]
Last commit should solve this... Method seems to have been added to support library in v26.1.0 only.

https://github.com/MFlisar/GDPRDialog/blob/1fb2da2e7ff6a81456548feb51e7c9effb3658ea/library/src/main/java/com/michaelflisar/gdprdialog/GDPR.java#L165-L186

You may try the it

**Comment by finalhit** [comment]
It's working properly now, many thanks for being so prompt!
