### ISSUE TITLE
How can i use in a Activity? not AppCompatActivity

### ISSUE THREAD

**Issue by ljwan12** [MFlisar/GDPRDialog#38]
How can i use in a Activity? not AppCompatActivity

**Comment by MFlisar** [comment]
You can't. There is no way to implement things for support and ddefault activities. All the functions with such a parameter would need to be written twice...

You could just fork the project and replace every support activity/fragment with default ones...

**Comment by MFlisar** [comment]
I close this for now.

Would be a nice extension to extract the function from the activity and dialog, put them into delegates and then reuse those delegates in the support and default versions of the `Dialog` and `Activity`. If someone wnats to do this, I would appreciate a pull reqeust
