### ISSUE TITLE
App crash Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by hazexzo** [MFlisar/GDPRDialog#41]
```
 public void callDamnedGDPR() {
        setup = new GDPRSetup(GDPRDefinitions.ADMOB)
                .withPrivacyPolicy("***")
                .withAllowNoConsent(true)
                .withPaidVersion(true)
                .withExplicitAgeConfirmation(true)
                .withCheckRequestLocation(false)
                .withBottomSheet(true)
                .withForceSelection(true)
                .withShortQuestion(true)
                .withLoadAdMobNetworks("pub-***")
        ;
        GDPR.getInstance().checkIfNeedsToBeShown(this, setup);
    }

    @Override
    public void onConsentNeedsToBeRequested(GDPRPreperationData gdprPreperationData) {
        GDPR.getInstance().showDialog(this, setup, gdprPreperationData.getLocation());
    }

```
The application falls as soon as I add this line to my code:
`        GDPR.getInstance().showDialog(this, setup, gdprPreperationData.getLocation());
`
Error:
<a href="http://piccy.info/view3/12366413/32e2d32a36e3bf4917cfe5e1db86fafd/" target="_blank"><img src="http://i.piccy.info/i9/f6c8e4b04129eb8ed2a9c283a98075b5/1527498981/8871/1247299/Screenshot_10_500.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-05-28-09-16/i9-12366413/500x72-r" target="_blank"><img src="http://i.piccy.info/a3/2018-05-28-09-16/i9-12366413/500x72-r/i.gif" alt="" border="0" /></a>

> Invoke-customs are only supported starting with Android O (--min-api 26)
> Message{kind=ERROR, text=Invoke-customs are only supported starting with Android O (--min-api 26), sources=[Unknown source file], tool name=Optional.of(D8)}
> 
> Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\**\Desktop\**\**\app\build\intermediates\transforms\androidGradleClassShrinker\debug\15
> 
> Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
> 
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
> 
> Caused by: com.android.tools.r8.utils.AbortException

- compileSdkVersion 27
- buildToolsVersion 27.0.3
- minSdkVersion 14
- targetSdkVersion 27

**Comment by MFlisar** [comment]
please try the solution posted here:

https://stackoverflow.com/questions/49891730/invoke-customs-are-only-supported-starting-with-android-0-min-api-26

**Comment by hazexzo** [comment]
Thanks. It helped.

**Comment by MFlisar** [comment]
PS: remove the `pub-` prefix here: `withLoadAdMobNetworks("pub-***")`, you only need to provide the number...

**Comment by Luklek** [comment]
Why you suggest to remove "pub-"? it isn't working for me with just the number (while is working fine with "pub-xxxxxxxxxxxx")
Has it been changed lately? I am on v1.2.1

**Comment by MFlisar** [comment]
I always used it without. No need to remove it if it works with the `pub-` prefix as well, maybe google's script is accepting both...

**Comment by Luklek** [comment]
Did you check the AdProviders you are getting without using "pub-" prefix?
I tried and if I use the "pub-" prefix, I am getting the proper list of AdProviders as defined in my AdMob account>
If I use without the "pub-" prefix, I am getting the standard full list of AdProviders even if my AdMob account is setup to show a custom set of providers.

**Comment by MFlisar** [comment]
I did not check this. I do not limit the Ad Providers... Good to know though, thanks for the info
