### ISSUE TITLE
something wrong with text2 layout

### ISSUE THREAD

**Issue by orium-dev** [MFlisar/GDPRDialog#43]
After restoring dialog from savedInstantceState (after clicking on 'Show Partners' or 'Admon') there is something wrong with layout.
![image](https://user-images.githubusercontent.com/8515110/40619265-0bab43da-629d-11e8-811d-caf6c6175d0c.png)

**Comment by MFlisar** [comment]
Can you reproduce this?

Try disabling this little function and check if this solves the issue:
https://github.com/MFlisar/GDPRDialog/blob/master/library/src/main/java/com/michaelflisar/gdprdialog/helper/GDPRViewManager.java#L418

**Comment by MFlisar** [comment]
Can you reproduce this? Try commenting out this line here and check if this helps:

https://github.com/MFlisar/GDPRDialog/blob/80203c748b40b9f4fdd8533e607f5e8aae195262/library/src/main/java/com/michaelflisar/gdprdialog/helper/GDPRViewManager.java#L317

**Comment by MFlisar** [comment]
I removed the text justification, new release should solve this
