### ISSUE TITLE
Definitions grouping

### ISSUE THREAD

**Issue by finalhit** [MFlisar/GDPRDialog#48]
Since some libraries are used for multiple purposes, I think we should group those together in GDPRDefinitions.java, as for Firebase, to avoid mentioning them several times in 'learn more' page.

So instead of:

`FLURRY_ANALYTICS = new GDPRNetwork(context, "Flurry Analytics", "https://policies.oath.com/us/en/oath/privacy/index.html", R.string.gdpr_type_analytics, false);`
`FLURRY_CRASH = new GDPRNetwork(context, "Flurry Crash", "https://policies.oath.com/us/en/oath/privacy/index.html", R.string.gdpr_type_crash, false);`
`FABRIC_CRASHLYTICS = new GDPRNetwork(context, "Fabric Crashlytics", "https://fabric.io/terms", R.string.gdpr_type_crash, false);`
`FABRIC_ANSWERS = new GDPRNetwork(context, "Fabric Answers", "https://fabric.io/terms", R.string.gdpr_type_analytics, false);`
        
to have:

`String flurry = "Flurry";`
`String flurryUrl = "https://policies.oath.com/us/en/oath/privacy/index.html";`
`FLURRY_ANALYTICS = new GDPRNetwork(context, flurry, flurryUrl, R.string.gdpr_type_analytics, false);`
`FLURRY_CRASH = new GDPRNetwork(context, flurry, flurryUrl, R.string.gdpr_type_crash, false);`
`String fabric = "Fabric";`
`String fabricUrl = "https://fabric.io/terms";`
`FABRIC_CRASHLYTICS = new GDPRNetwork(context, fabric, fabricUrl, R.string.gdpr_type_crash, false);`
`FABRIC_ANSWERS = new GDPRNetwork(context, fabric, fabricUrl, R.string.gdpr_type_analytics, false);`

**Comment by MFlisar** [comment]
Grouoing is done automatically anyways if the names are equal. So your change does make sense and the rest should work automatically... Would you mind making a pull request? I would accept it...

**Comment by finalhit** [comment]
Done https://github.com/MFlisar/GDPRDialog/pull/50
