### ISSUE TITLE
Localytics & Adobe

### ISSUE THREAD

**Issue by finalhit** [MFlisar/GDPRDialog#49]
`String localytics = "Localytics";`
`String localyticsUrl = "https://www.localytics.com/privacy-policy/";`
`LOCALYTICS_ANALYTICS = new GDPRNetwork(context, localytics, localyticsUrl, R.string.gdpr_type_analytics, false);`
`LOCALYTICS_MESSAGING = new GDPRNetwork(context, localytics, localyticsUrl, R.string.gdpr_type_notifications, false);`

`<string name="gdpr_type_authorization">authorization</string>`

`String adobe = "Adobe";`
`String adobeUrl = "https://www.adobe.com/privacy/policy.html";`
`ADOBE_ID = new GDPRNetwork(context, adobe, adobeUrl, R.string.gdpr_type_authorization, false);`

**Comment by MFlisar** [comment]
Same here, adding this to a pull request would be nice

**Comment by finalhit** [comment]
Done https://github.com/MFlisar/GDPRDialog/pull/50
