### ISSUE TITLE
Allow to selectively mark services as optional

### ISSUE THREAD

**Issue by MFlisar** [MFlisar/GDPRDialog#5]
In v0.5 I remove the ability to selectively accept single services.

Many times you only use services that must be accepted anyways, as the app must be bought otherwise (to remove ads) or can't work anyways (e.g. without the cloud database). 

So for many people this should be sufficiant...

Feel free to add this feature again at anytime...

**Comment by foreza** [comment]
Hey @MFlisar,

It would definitely create more headache by letting the user pick and choose single services, IMO. When they download the app, the publisher is responsible for letting them review all the necessary permissions / data usage from my understanding. If even 1 line is something that makes the user uncomfortable, they can opt out / not use the app in it's entirety. 

I agree with your assessment that for many people, this would be sufficient.

**Comment by MFlisar** [comment]
Someone was requesting this on reddit... And I had implemented it already. But with current strings it would not work so I simply removed it.

Two usecases I see:

**Optional feature**
If you are using ads + cloud database and you offer a local mode as well. There you could make the cloud database service optional...

**Stepper layout**
Some apps show the consent dialog with a stepper. If this would be added, the optional feature would be just a small extra

I won't add this as I don't any of this and I made the library as generic and reuseable as possible already anyways

**Comment by MFlisar** [comment]
Won't add this for now anyways, so I close it again
