### ISSUE TITLE
withLoadAdMobNetworks

### ISSUE THREAD

**Issue by finalhit** [MFlisar/GDPRDialog#51]
How exactly should be withLoadAdMobNetworks used?

Is it really necessary to show all AdMob's 200 subproviders?

**Comment by MFlisar** [comment]
Simply pass in one or more publisher ids, e.g. like following_

    setup.withLoadAdMobNetworks("pub-0123456789012345");

It's not necessary, it's up to you if you want this or not. If the loading fails or times out, the default info url will be shown with all default google ad networks: https://support.google.com/admob/answer/9012903

**Comment by finalhit** [comment]
I did pass publisher ID, but nothing new is displayed in GDPR dialog?

**Comment by MFlisar** [comment]
If you click "Learn more about..." in the dialog you should see a list of your ad providers instead of "AdMob (Show partners)"... Only if you also have added the admob ad network

**Comment by MFlisar** [comment]
I think this is solved, if you have more question, feel free to ask
