### ISSUE TITLE
Title of message - free / cheap related text

### ISSUE THREAD

**Issue by Terence-D** [MFlisar/GDPRDialog#56]
For my application I'm only using crashalytics / analytics, this is both in the free and paid versions (and both are optional).  The current title will imply the app is free or cheap because of this, but if i set it to Paid which allows it to say cheap for my paid apps, it automatically inserts a button to go to the paid version - which I don't want.  If I don't include that it says free, when the app may not have been free.  

I can't alter the text because because it expects to insert free or cheap via getString.

I modified my own version to just remove that part of the title so it now only has the first sentence:
Original:
     <string name="gdpr_dialog_text1">We care about your privacy and data security. We keep this app %1$s by using third party services.</string>
My version:
     <string name="gdpr_dialog_text1">We care about your privacy and data security.</string>

Is there some way to make the second sentence optional?

**Comment by MFlisar** [comment]
I checked the translations and every language is seperating the two sentences, so this is easy...

Checkout the new `withShowPaidOrFreeInfoText` function in the master branch...
