### ISSUE TITLE
Plurals should be used in slightly different way.

### ISSUE THREAD

**Issue by thubalek** [MFlisar/GDPRDialog#6]
I tried to translate your string to Czech but there is a problem. 

In Czech we have not only different word for plural and singular (and singulars dependent on number of items) but we have also different words depending where in the sentence they are.

I was quite a creative but I can't anyhow handle this situation:

![gdpr preklad](https://user-images.githubusercontent.com/1260262/40423641-7a4089a8-5e93-11e8-8341-332b284f5ebe.png)

this is translation of the word Service (in Czech _služba_ singular, _služby_ plural). But there is necessary to have this word either in form _služba_/_služby_ in first occurrence and _službě/službám_ in second occurence.

I would suggest not to try include plurals into strings but to put whole sentences into `plurals.xml` file.
It is more flexible and I'm sure it will also work better in other languages.

**Comment by MFlisar** [comment]
Could this be solved be defining two plurals for service as well?

Making sentences would probalby double the amount of string I would have to write...

**Comment by thubalek** [comment]
That solution will work for Czech. But next time somebody will come with different language and we will need more changes. And translators will have to update their translations too.

I think there are just a few sentences that are affected by plurals/singulars. It is not a big deal.

**Comment by MFlisar** [comment]
Actually you're right, it's only one big sentence with a log of plural/singular occurences...

Just changed this

**Comment by thubalek** [comment]
Cool. I'll make pull request with Czech translation tomorrow.
