### ISSUE TITLE
AdMob providers not showing

### ISSUE THREAD

**Issue by Luklek** [MFlisar/GDPRDialog#61]
I just noticed that I can't load the AdMob providers list. It always display the "Show partners" instead of the full list of AdProviders as fetched from my AdMob publisherID.
I tested with the demo app too and it's the same.
Also if I manually opened the url (with my pubID) and the txt includes the full list of "companies", "company_name" and "policy_url".

Am I doing something wrong?

**Comment by MFlisar** [comment]
Found the issue. When adding the alternative location checks I forgot to save the retrieved list of ad providers in the result...

Fixed in the current master branch
