### ISSUE TITLE
How to check if the library is initialized 

### ISSUE THREAD

**Issue by master94ga** [MFlisar/GDPRDialog#62]
Hello, how do I know if the library is already initialized?

If is not `GDPR.getInstance().getConsentState().getConsent()` cause a crash, and I want do to if the library is initialized launch this code, else initialize the library and after launch the code.

I did something like this but maybe there is a better way:

      
```
private static boolean GDPR_initialized = false;

 if (!GDPR_initialized){
            GDPR.getInstance().init(activity);
            GDPR_initialized = true;
        }
```

**Comment by MFlisar** [comment]
added a function to the master branch for this

https://github.com/MFlisar/GDPRDialog/blob/2235163dc75411244e44539e78babacf130439a0/library/src/main/java/com/michaelflisar/gdprdialog/GDPR.java#L231

In general, you should just initialise GDPR in your *application*, no need to check this if you do it like this...
