### ISSUE TITLE
Can't Disable Certain Properties 

### ISSUE THREAD

**Issue by vedantroy** [MFlisar/GDPRDialog#64]
I have the following setup object in my `onCreate` method:

```
        GDPR.getInstance().init(this)
        setup = GDPRSetup(GDPRDefinitions.FIREBASE_CRASH)
                .withShowPaidOrFreeInfoText(false)
                .withExplicitAgeConfirmation(false)
                .withShortQuestion(false)
```

I later show the dialog like this when a button is clicked:

`            GDPR.getInstance().showDialog(this, setup, GDPRLocation.UNDEFINED)
`

However, the "Can we continue to use your data for these purposes?" and "By agreeing, you are confirming that you are over the age of 16." messages are still showing.

**Comment by robigangsta** [comment]
Agree, the customization seemed great but at the deeper look it turns out to be horrible. You should allow users to change text because you can't have one text for all apps. It just doesn't fit.

**Comment by vedantroy** [comment]
@robigangsta I think it may just be a big in the library. Afterall, the API suggests it is possible to disable various elements.

**Comment by MFlisar** [comment]
You can always overwrite ANY resource in your app, android offers this out of the box.

I would not mind if someone implements `withMainText(String)`, `withAgeText(String)` and similar to customise the texts via the builder as well...

**Comment by MFlisar** [comment]
Newest version allows to overwrite all texts of the main view:

https://github.com/MFlisar/GDPRDialog/blob/ed2f8655040147bf2ee553b22ece5f1e02e95a6e/app/src/main/java/com/michaelflisar/gdprdialog/demo/SetupActivity.java#L169-L187
