### ISSUE TITLE
"NO, THANK YOU" text bugged showing "NO THANK YOU, I WANT TO BUY THE APP" even when paid version is disabled.

### ISSUE THREAD

**Issue by robigangsta** [MFlisar/GDPRDialog#65]
Hi,

I noticed that there is a rather critical bug
No consent button should show text: NO, THANK YOU, but instead it;s always showing NO, THANK YOU, I WANT TO BUY THE APP

This is rather annoying as I don't have paid option, this is how I set my code:|

        GDPR.getInstance().init(this);

         setup = new GDPRSetup(GDPRDefinitions.ADMOB,GDPRDefinitions.APPNEXT,GDPRDefinitions.UNITY) // add all networks you use to the constructor, signature is `GDPRSetup(GDPRNetwork... adNetworks)`
                // everything is optional, but you should at least provide your policy
                .withPrivacyPolicy("https://brprivacypolicyblog.wordpress.com/")
                .withAllowNoConsent(false)
                .withPaidVersion(false)
                .withExplicitAgeConfirmation(false)
                .withCheckRequestLocation(GDPRLocationCheck.DEFAULT) // pass in an array of location check methods, predefined arrays like `DEFAULT` and `DEFAULT_WITH_FALLBACKS` do exists
                .withCheckRequestLocationTimeouts(2000, 2000)
                .withBottomSheet(false)
                .withForceSelection(true)
                .withShortQuestion(true)
                .withLoadAdMobNetworks("pub-3253084521349460") // e.g. "pub-0123456789012345"
                .withNoToolbarTheme(true)

         // show the info that this app is cheap/free based on the networks or hide it
                ;
        //GDPR.getInstance().checkIfNeedsToBeShown(this /* extends AppCompatActivity & GDPR.IGDPRCallback */, setup);

        GDPR.getInstance().showDialog(this, setup, GDPRLocation.IN_EAA_OR_UNKNOWN);

and it's still showing like that.

**Comment by MFlisar** [comment]
Remove `.withPaidVersion(false)`. This function is a little bit confusing... Check out it's documentation here:

https://github.com/MFlisar/GDPRDialog/blob/292d6c927f86f1fd81a135ee5dc2c73be61f8103/library/src/main/java/com/michaelflisar/gdprdialog/GDPRSetup.java#L65-L75

Don't use this function if you do not offer a paid version...
