### ISSUE TITLE
Alignment of texts

### ISSUE THREAD

**Issue by thubalek** [MFlisar/GDPRDialog#7]
Would it be possible somehow make alignment of texts more consistent? See

![image](https://user-images.githubusercontent.com/1260262/40435185-65e4173c-5eb0-11e8-8223-4b0343518a3f.png)

What do you think?

This is not critical, just a feedback. I'm OK if you close it with WONTFIX.

**Comment by MFlisar** [comment]
What would you suggest? Text alignment is not that easy on android (block style for example)... At least not integrated in the default `TextView` before API 26...

**Comment by MFlisar** [comment]
Added following justification code for the main text. On android API >=26 I use the native justification that was added in this version, on android API >= 23 && API < 26, I use a manual method and on older API versions I can't do anything...

https://github.com/MFlisar/GDPRDialog/blob/d1aa0e4a4b9fdc5c82f19c922b2d3c8082371154/library/src/main/java/com/michaelflisar/gdprdialog/helper/GDPRViewManager.java#L370-L387
