### ISSUE TITLE
Failed to resolve: com.github.MFlisar:GDPRDialog:1.2.6

### ISSUE THREAD

**Issue by boypanjaitan15** [MFlisar/GDPRDialog#74]
Error:(123, 20) Failed to resolve: com.github.MFlisar:GDPRDialog:1.2.6

Can anyone help me? why I got this error, but on another project it's working as well

**Comment by MFlisar** [comment]
you probably just forgot to add jitpack to your repositories

**Comment by MFlisar** [comment]
close, issue is probably solved
