### ISSUE TITLE
Texts in buttons are very small

### ISSUE THREAD

**Issue by cezaryjurkiweicz** [MFlisar/GDPRDialog#85]
Like in picture: https://ibb.co/svTbwYZ

**Comment by MFlisar** [comment]
Do you use a material theme in your app? Like the demo does:

https://github.com/MFlisar/GDPRDialog/blob/34461030fa4bbade943973c17d2632997a7c4c00/app/src/main/res/values/styles.xml#L4

Only a material theme will work correctly (or use the bridge versions of them to get a theme that works with material and app compat)

**Comment by cezaryjurkiweicz** [comment]
Yeah, that was the problem. But I think it was ok in prevoius version... not sure

**Comment by MFlisar** [comment]
I wrote it into the release notes: https://github.com/MFlisar/GDPRDialog/releases/tag/1.4.0 So it was working until this version with app compat theme.

Actually, it was a bug before, android x should be used with material themes anyways
