### ISSUE TITLE
Choice Button on GDPR Dialog

### ISSUE THREAD

**Issue by anchorite13** [MFlisar/GDPRDialog#88]
How can I choose to show only 2 choice. Agree and No thank you. If I choose withPaidVersion(false) there are 3 choice which No ads at all is not good. I choose true then I got Agree and No Thank you. But suddenly the 3 option popup, No I want to buy the app. Is there a way to change the button? Thanks

**Comment by MFlisar** [comment]
Which options would you like to offer? "personal ads" + "no, I don't want to use this app"? What are the 2 options you want?

**Comment by anchorite13** [comment]
I just want Personal ads and non-personal ads. I don't want "I want to buy the app" or "No ad at all". Thanks MFlisar.

**Comment by MFlisar** [comment]
Check out the demo app please, option 2.1 in it seems to be what you want

**Comment by anchorite13** [comment]
Thanks MFlisar.
